### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by roshan-bajgain**
## React capstone project - Metrics webapp
- Select the API you are going to use.
- Build files structure for your React app.
- Prepare routes and navigation in your app.
- Make sure that a user can display a list of items and filter them. Data should come from the API.
- Create the tests for the application.
- Style your components to match the design provided.
- Deploy the project and test for final details.
- Record a video for your project.
- Create a good README and PR description.

### CODE REVIEW

**Comment by roshan-bajgain** [comment]
## Video
[loom video](https://www.loom.com/share/6aacaaed0c6740ee870bb9203d6998d4)

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @roshan-bajgain 

Good job working on the project so far! 
✔️  Your live link works well.
✔️ Your app is a single page application.
✔️ You used the colors and design provided.
However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [x] Your video presentation currently misses a piece of code you are proud of or find interesting, kindly add this to your video.
- [x] There are still some boilerplates generated by CRA in your public folder, kindly delete them.
- [x] While you created a search bar to allow categories to be filtered, the search bar does not work. When I try to search for a given country, it does not produce any result. Please fix this so that I can search for a country using the search bar. This would completely fulfill the requirement.
- [x] When I run your tests, some of them fail or give errors as shown below:
Screenshot 2022-02-03 at 15 42 51
Screenshot 2022-02-03 at 15 43 08
Screenshot 2022-02-03 at 15 43 16
Screenshot 2022-02-03 at 15 43 50

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by roshan-bajgain** [comment]
## This is a new video as the reviewer said to make another video.
[loom-video](https://www.loom.com/share/c9b536c557c842d89d54bfce4589dce6)

**Review by Emmyn5600 — APPROVED** [review]
STATUS: APPROVED :partying_face: 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
